# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 067d3a0491e666fd43071e7f6b129175642d00c3f48d457ccb374ac1d4c153ecefa513e60cd5ab085ffb3f933b5002a75691f72322e31f761973cc69d35d4860

test:
  secret_key_base: fd959242c9c7a08ec041b637ddf3f4f036666a02df5a617fd507f7b5af4337e5382ee2df281551ad267dd4b3987fb0d144fb42e4a04c132d060b21e5bf41e3cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
